name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -d "monitoring-platform" ]; then
              git clone git@github.com:yourusername/monitoring-platform.git
              cd monitoring-platform
            else
              cd monitoring-platform
              git pull origin main
            fi
            docker-compose down
            docker-compose up -d --build

